## The use of this source code is governed by the LICENSE file located in this
## project's root directory.

name: generate_screens
publish_to: none

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.0.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  df_generate_header_comments:
    path: ../
  df_log: ^0.2.1