##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_generate_header_comments
description: A tool to generate header comments for your source files.
version: 0.1.2
repository: https://github.com/robmllze/df_generate_header_comments
funding:
  - https://www.buymeacoffee.com/robmllze
topics:
  - source-gen
  - build-runner
  - code-generation
  - comments
  - header-comments

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  df_config: ^0.4.0
  df_gen_core: ^0.2.8
  df_log: ^0.2.1
  path: ^1.9.0
  args: ^2.5.0

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8

## -----------------------------------------------------------------------------

executables:
  genhdr: genhdr
  genhdr-df: genhdr-df
  genhdr-v1: genhdr-v1
